# Generated by Django 3.2.9 on 2022-09-08 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webtoons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=1000)),
                ('select1', models.CharField(max_length=100)),
                ('select2', models.CharField(max_length=100)),
                ('select3', models.CharField(max_length=100)),
                ('select4', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('validation', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='member_quizzes', to=settings.AUTH_USER_MODEL)),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoon_quizzes', to='webtoons.webtoon')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=1000)),
                ('character_type', models.IntegerField()),
                ('selected_count', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(related_name='member_characters', to=settings.AUTH_USER_MODEL)),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoon_characters', to='webtoons.webtoon')),
            ],
        ),
    ]
