<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-09-16 02:10
=======
# Generated by Django 4.1.1 on 2022-09-16 02:17
>>>>>>> 86fecf2 (Fix game api ver_0.5)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]
=======
    dependencies = []
>>>>>>> 86fecf2 (Fix game api ver_0.5)

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
<<<<<<< HEAD
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('nickname', models.CharField(default='', max_length=100, unique=True)),
                ('gender', models.CharField(default='', max_length=100)),
                ('birth', models.IntegerField(default=0)),
                ('profile_image_url', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
                ('liked_thumnail', models.CharField(max_length=100)),
                ('resigned_time', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
=======
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(default="", max_length=255, unique=True)),
                ("nickname", models.CharField(default="", max_length=100, unique=True)),
                ("gender", models.CharField(default="", max_length=100)),
                ("birth", models.IntegerField(default=0)),
                ("profile_image_url", models.TextField(blank=True)),
                ("count", models.IntegerField(default=0)),
                ("liked_thumnail", models.CharField(max_length=100)),
                ("resigned_time", models.DateTimeField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
>>>>>>> 86fecf2 (Fix game api ver_0.5)
            },
        ),
    ]
