<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-09-16 02:10
=======
# Generated by Django 4.1.1 on 2022-09-16 02:17
>>>>>>> 86fecf2 (Fix game api ver_0.5)
=======
# Generated by Django 4.1 on 2022-09-19 04:41
>>>>>>> f807105 (fix: makemigrations 다시)
=======
# Generated by Django 4.1.1 on 2022-09-16 05:21
>>>>>>> 91db506 (feat : 회원정보수정)
=======
# Generated by Django 4.1.1 on 2022-09-19 04:16
>>>>>>> 5784305 (Add ToonBTI views.py/question definition)
=======
# Generated by Django 4.1 on 2022-09-19 08:52
>>>>>>> d2a7f0d (fix: makemigrations 재가동)
=======
# Generated by Django 4.1.1 on 2022-09-20 06:39
>>>>>>> f81c1cd (fix: 회원 로그인/로그아웃 등 수정)
=======
# Generated by Django 4.1.1 on 2022-09-19 08:01
>>>>>>> 2711023 (feat: 웹툰 찜 기능 구현 (50%))
=======
# Generated by Django 4.1.1 on 2022-09-22 08:48
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
=======
# Generated by Django 4.1.1 on 2022-09-26 07:50
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
=======
        ("webtoons", "__first__"),
>>>>>>> 91db506 (feat : 회원정보수정)
=======
        ('webtoons', '__first__'),
>>>>>>> f81c1cd (fix: 회원 로그인/로그아웃 등 수정)
    ]
=======
    dependencies = []
>>>>>>> 86fecf2 (Fix game api ver_0.5)

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    dependencies = [
        ('webtoons', '__first__'),
    ]
=======
    dependencies = []
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
=======
    dependencies = [
    ]
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 5784305 (Add ToonBTI views.py/question definition)
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
=======
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
>>>>>>> f81c1cd (fix: 회원 로그인/로그아웃 등 수정)
=======
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('nickname', models.CharField(default='', max_length=100, unique=True)),
                ('gender', models.CharField(default='', max_length=100)),
                ('birth', models.IntegerField(default=0)),
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
                ('profile_image_url', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
<<<<<<< HEAD
                ('liked_thumnail', models.CharField(max_length=100)),
=======
=======
                ('profile_image_id', models.IntegerField(blank=True, default=0)),
>>>>>>> d2a7f0d (fix: makemigrations 재가동)
=======
                ('profile_image_id', models.IntegerField(blank=True, default=0)),
>>>>>>> 2711023 (feat: 웹툰 찜 기능 구현 (50%))
                ('liked_thumbnail', models.CharField(max_length=100)),
>>>>>>> 5784305 (Add ToonBTI views.py/question definition)
=======
                ('profile_image_id', models.IntegerField(blank=True, default=0)),
                ('liked_thumbnail', models.CharField(max_length=100)),
>>>>>>> f81c1cd (fix: 회원 로그인/로그아웃 등 수정)
=======
                ('profile_image_id', models.IntegerField(blank=True, default=0)),
                ('liked_thumbnail', models.CharField(max_length=100)),
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)
                ('resigned_time', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
            ],
            options={
                'abstract': False,
=======
=======
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
<<<<<<< HEAD
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
=======
                ("id", models.AutoField(primary_key=True, serialize=False)),
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
                ("email", models.EmailField(default="", max_length=255, unique=True)),
                ("nickname", models.CharField(default="", max_length=100, unique=True)),
                ("gender", models.CharField(default="", max_length=100)),
                ("birth", models.IntegerField(default=0)),
<<<<<<< HEAD
                ("profile_image_url", models.TextField(blank=True)),
                ("count", models.IntegerField(default=0)),
                ("liked_thumnail", models.CharField(max_length=100)),
=======
                ("profile_image_id", models.IntegerField(blank=True, default=0)),
                ("liked_thumbnail", models.CharField(max_length=100)),
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
                ("resigned_time", models.DateTimeField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
<<<<<<< HEAD
            ],
            options={
                "abstract": False,
>>>>>>> 86fecf2 (Fix game api ver_0.5)
=======
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(default="", max_length=255, unique=True)),
                ("nickname", models.CharField(default="", max_length=100, unique=True)),
                ("gender", models.CharField(default="", max_length=100)),
                ("birth", models.IntegerField(default=0)),
                ("profile_image_url", models.TextField(blank=True)),
                ("count", models.IntegerField(default=0)),
                ("liked_thumnail", models.CharField(max_length=100)),
                ("resigned_time", models.DateTimeField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "liked_webtoons",
                    models.ManyToManyField(
                        related_name="liked_webtoon_users", to="webtoons.webtoon"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="tag_users", to="webtoons.tag"),
                ),
                (
                    "view_webtoons",
                    models.ManyToManyField(
                        related_name="view_webtoon_users", to="webtoons.webtoon"
                    ),
                ),
            ],
            options={
                "abstract": False,
>>>>>>> 91db506 (feat : 회원정보수정)
=======
                ('liked_webtoons', models.ManyToManyField(related_name='liked_webtoon_users', to='webtoons.webtoon')),
                ('tags', models.ManyToManyField(related_name='tag_users', to='webtoons.tag')),
                ('view_webtoons', models.ManyToManyField(related_name='view_webtoon_users', to='webtoons.webtoon')),
            ],
            options={
                'abstract': False,
>>>>>>> 5784305 (Add ToonBTI views.py/question definition)
=======
                ('liked_webtoons', models.ManyToManyField(related_name='liked_webtoon_users', to='webtoons.webtoon')),
                ('tags', models.ManyToManyField(related_name='tag_users', to='webtoons.tag')),
                ('view_webtoons', models.ManyToManyField(related_name='view_webtoon_users', to='webtoons.webtoon')),
            ],
            options={
                'abstract': False,
>>>>>>> f81c1cd (fix: 회원 로그인/로그아웃 등 수정)
=======
            ],
            options={
                "abstract": False,
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
=======
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member_View_Webtoons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_member_view_webtoons',
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)
            },
        ),
    ]
