<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-09-16 02:10
=======
# Generated by Django 4.1.1 on 2022-09-16 02:17
>>>>>>> 86fecf2 (Fix game api ver_0.5)
=======
# Generated by Django 4.1 on 2022-09-19 04:41
>>>>>>> f807105 (fix: makemigrations 다시)
=======
# Generated by Django 4.1.1 on 2022-09-22 08:48
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
=======
# Generated by Django 4.1.1 on 2022-09-26 07:50
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)
=======
# Generated by Django 4.1.1 on 2022-09-27 01:49
>>>>>>> c5812ab (feat : rating model추가, rating views 수정)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        ('accounts', '0001_initial'),
        ('webtoons', '0001_initial'),
=======
        ("accounts", "0001_initial"),
        ("webtoons", "0001_initial"),
>>>>>>> 86fecf2 (Fix game api ver_0.5)
=======
        ('webtoons', '0001_initial'),
        ('accounts', '0001_initial'),
>>>>>>> f807105 (fix: makemigrations 다시)
=======
        ("accounts", "0001_initial"),
        ("webtoons", "0001_initial"),
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
=======
        ('accounts', '0001_initial'),
        ('webtoons', '0001_initial'),
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)
=======
        ("accounts", "0001_initial"),
        ("webtoons", "0001_initial"),
>>>>>>> c5812ab (feat : rating model추가, rating views 수정)
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
            model_name='member',
            name='liked_webtoons',
            field=models.ManyToManyField(related_name='liked_webtoon_users', to='webtoons.webtoon'),
=======
            model_name="member_view_webtoons",
            name="webtoon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webtoons.webtoon"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="liked_webtoons",
            field=models.ManyToManyField(
                related_name="liked_webtoon_users", to="webtoons.webtoon"
            ),
>>>>>>> c5812ab (feat : rating model추가, rating views 수정)
        ),
        migrations.AddField(
            model_name="member",
            name="tags",
            field=models.ManyToManyField(related_name="tag_users", to="webtoons.tag"),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='member',
            name='view_webtoons',
            field=models.ManyToManyField(related_name='view_webtoon_users', to='webtoons.webtoon'),
<<<<<<< HEAD
=======
=======
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
            model_name="member",
            name="liked_webtoons",
            field=models.ManyToManyField(
                related_name="liked_webtoon_users", to="webtoons.webtoon"
            ),
=======
            model_name='member_view_webtoons',
            name='webtoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtoons.webtoon'),
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)
        ),
        migrations.AddField(
            model_name='member',
            name='liked_webtoons',
            field=models.ManyToManyField(related_name='liked_webtoon_users', to='webtoons.webtoon'),
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name="member",
            name="view_webtoons",
            field=models.ManyToManyField(
                related_name="view_webtoon_users", to="webtoons.webtoon"
            ),
<<<<<<< HEAD
>>>>>>> 86fecf2 (Fix game api ver_0.5)
=======
>>>>>>> f807105 (fix: makemigrations 다시)
=======
>>>>>>> c4b2854 (feat: 웹툰 이미지 검색 api 구현)
=======
            model_name='member',
            name='tags',
            field=models.ManyToManyField(related_name='tag_users', to='webtoons.tag'),
        ),
        migrations.AddField(
            model_name='member',
            name='view_webtoons',
            field=models.ManyToManyField(through='accounts.Member_View_Webtoons', to='webtoons.webtoon'),
>>>>>>> c9803bc (fix : profile 수정, email,nickname 중복확인 수정)
=======
            model_name="member",
            name="view_webtoons",
            field=models.ManyToManyField(
                through="accounts.Member_View_Webtoons", to="webtoons.webtoon"
            ),
>>>>>>> c5812ab (feat : rating model추가, rating views 수정)
        ),
    ]
