<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-09-16 02:10
=======
# Generated by Django 4.1.1 on 2022-09-16 02:17
>>>>>>> 86fecf2 (Fix game api ver_0.5)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('accounts', '0001_initial'),
        ('webtoons', '0001_initial'),
=======
        ("accounts", "0001_initial"),
        ("webtoons", "0001_initial"),
>>>>>>> 86fecf2 (Fix game api ver_0.5)
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='member',
            name='liked_webtoons',
            field=models.ManyToManyField(related_name='liked_webtoon_users', to='webtoons.webtoon'),
        ),
        migrations.AddField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(related_name='tag_users', to='webtoons.tag'),
        ),
        migrations.AddField(
            model_name='member',
            name='view_webtoons',
            field=models.ManyToManyField(related_name='view_webtoon_users', to='webtoons.webtoon'),
=======
            model_name="member",
            name="liked_webtoons",
            field=models.ManyToManyField(
                related_name="liked_webtoon_users", to="webtoons.webtoon"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="tags",
            field=models.ManyToManyField(related_name="tag_users", to="webtoons.tag"),
        ),
        migrations.AddField(
            model_name="member",
            name="view_webtoons",
            field=models.ManyToManyField(
                related_name="view_webtoon_users", to="webtoons.webtoon"
            ),
>>>>>>> 86fecf2 (Fix game api ver_0.5)
        ),
    ]
