# Generated by Django 4.1.1 on 2022-09-26 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_view_webtoons',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_viewed_webtoons', to=settings.AUTH_USER_MODEL),
        ),
    ]
