# Generated by Django 4.1.1 on 2022-09-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_today',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
