# Generated by Django 4.1.1 on 2022-09-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_liked_thumnail_member_liked_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='count',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='member',
            name='profile_image_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
