# Generated by Django 3.2.9 on 2022-09-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220916_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='resigned_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
