# Generated by Django 4.1.1 on 2022-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_member_count_remove_member_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
