# Generated by Django 4.1.1 on 2022-09-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DrawClassify",
            new_name="DrawClassifing",
        ),
    ]
