# Generated by Django 4.1 on 2022-09-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='validation',
        ),
        migrations.RemoveField(
            model_name='webtoon',
            name='image_type',
        ),
        migrations.AddField(
            model_name='webtoon',
            name='image_type1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='image_type2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='image_type3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='image_type4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='image_type5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='image_type6',
            field=models.FloatField(null=True),
        ),
    ]
