# Generated by Django 4.1.1 on 2022-09-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0002_rename_drawclassify_drawclassifing"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DrawClassifing",
            new_name="DrawClassifies",
        ),
    ]
