# Generated by Django 4.1.1 on 2022-09-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0003_rename_drawclassifing_drawclassifies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DrawClassifies",
            new_name="DrawClassify",
        ),
    ]
